SELECT * FROM STATION;

SELECT * FROM STATION
WHERE LAT_N > 39.7;

SELECT ID, CITY, STATE FROM STATION;

SELECT ID, CITY, STATE FROM STATION
WHERE LAT_N > 39.7;

CREATE TABLE STATS
(ID INTEGER REFERENCES STATION(ID),
MONTH INTEGER CHECK (MONTH BETWEEN 1 AND 12),
TEMP_F REAL CHECK (TEMP_F BETWEEN -80 AND 150),
RAIN_I REAL CHECK (RAIN_I BETWEEN 0 AND 100),
PRIMARY KEY (ID, MONTH));
