#!/usr/bin/env python3
"""
Interactive animated scatter plot of FICO vs LTV using Plotly Express.

This produces a high-quality interactive HTML animation with:
- Play / Pause controls
- Quarter scrubber slider
- Hover tooltips with full loan details
- Legend filtering
- Zoom / pan

Much easier to explore than a GIF, and great for presentations/dashboards.
"""

import pandas as pd
import plotly.express as px
import plotly.io as pio

# Use a clean modern template
pio.templates.default = "plotly_white"

# Load the dataset (generated by generate_data.py or the R script)
df = pd.read_csv("fico_ltv_sample_data.csv")

# Nice consistent color map (matches the R script)
color_map = {
    "Super Prime": "#1a9850",   # dark green
    "Prime":       "#91cf60",   # light green
    "Near Prime":  "#fc8d59",   # orange
    "Subprime":    "#d73027"    # red
}

# Create the animated scatter
fig = px.scatter(
    df,
    x="fico",
    y="ltv",
    color="risk_segment",
    size="loan_amount",
    size_max=18,
    hover_name="loan_id",
    hover_data={
        "fico": True,
        "ltv": True,
        "loan_amount": ":$,.0f",
        "purpose": True,
        "quarter": False,        # already in animation frame
        "risk_segment": False,
    },
    color_discrete_map=color_map,
    category_orders={
        "risk_segment": ["Super Prime", "Prime", "Near Prime", "Subprime"],
        "quarter": ["2023-Q1", "2023-Q2", "2023-Q3", "2023-Q4",
                    "2024-Q1", "2024-Q2", "2024-Q3", "2024-Q4"]
    },
    animation_frame="quarter",
    animation_group="loan_id",   # keeps points consistent across frames
    range_x=[575, 855],
    range_y=[48, 107],
    title="FICO Score vs. Loan-to-Value Ratio<br><sup>Mortgage Originations — 2023-Q1 to 2024-Q4 (synthetic data)</sup>",
    labels={
        "fico": "FICO Credit Score",
        "ltv": "Loan-to-Value Ratio (%)",
        "risk_segment": "Credit Segment",
        "loan_amount": "Loan Amount",
    },
    height=780,
    width=1180,
)

# Improve the animation controls and layout
fig.update_layout(
    legend=dict(
        title="Credit Segment",
        orientation="v",
        yanchor="top",
        y=0.98,
        xanchor="left",
        x=0.015,
        font=dict(size=11),
        bgcolor="rgba(255,255,255,0.85)",
    ),
    margin=dict(l=60, r=30, t=80, b=70),
    font=dict(size=13),
    title=dict(font=dict(size=20, color="#222222")),
    xaxis=dict(
        tick0=600,
        dtick=40,
        gridcolor="#e8e8e8",
        zeroline=False,
    ),
    yaxis=dict(
        tick0=50,
        dtick=10,
        gridcolor="#e8e8e8",
        zeroline=False,
        tickformat=".0f",   # will be followed by % in hover
    ),
    updatemenus=[{
        "type": "buttons",
        "showactive": False,
        "y": 0.55,
        "x": 0.02,
        "xanchor": "left",
        "buttons": [
            {
                "label": "▶ Play",
                "method": "animate",
                "args": [None, {
                    "frame": {"duration": 720, "redraw": True},
                    "fromcurrent": True,
                    "transition": {"duration": 280, "easing": "cubic-in-out"}
                }]
            },
            {
                "label": "⏸ Pause",
                "method": "animate",
                "args": [[None], {
                    "frame": {"duration": 0, "redraw": False},
                    "mode": "immediate",
                    "transition": {"duration": 0}
                }]
            }
        ]
    }],
    sliders=[{
        "currentvalue": {
            "prefix": "Origination Quarter:  ",
            "font": {"size": 15, "color": "#1a1a1a"},
            "visible": True,
            "xanchor": "center"
        },
        "pad": {"t": 50},
        "len": 0.88,
        "x": 0.06,
    }]
)

# Add subtle reference lines as shapes (they persist across frames)
shapes = []
# Vertical FICO thresholds
for x in [620, 680, 720, 760]:
    shapes.append(dict(
        type="line", x0=x, x1=x, y0=48, y1=107,
        line=dict(color="#888888", width=1, dash="dot"), opacity=0.45,
        layer="below"
    ))
# Horizontal LTV thresholds
for y in [80, 90, 97]:
    shapes.append(dict(
        type="line", x0=575, x1=855, y0=y, y1=y,
        line=dict(color="#888888", width=1, dash="dot"), opacity=0.45,
        layer="below"
    ))

fig.update_layout(shapes=shapes)

# Add small annotations for the reference lines
annotations = [
    dict(x=622, y=49.5, text="620", showarrow=False, font=dict(size=10, color="#666666")),
    dict(x=682, y=49.5, text="680", showarrow=False, font=dict(size=10, color="#666666")),
    dict(x=722, y=49.5, text="720", showarrow=False, font=dict(size=10, color="#666666")),
    dict(x=762, y=49.5, text="760", showarrow=False, font=dict(size=10, color="#666666")),
    dict(x=578, y=80.5, text="80% LTV", showarrow=False, font=dict(size=9.5, color="#666666"), textangle=-90),
    dict(x=578, y=90.5, text="90% LTV", showarrow=False, font=dict(size=9.5, color="#666666"), textangle=-90),
]
fig.update_layout(annotations=annotations)

# Make size legend more compact
fig.update_layout(legend_itemsizing="constant")

# Save as standalone interactive HTML (opens beautifully in any browser)
output_html = "fico_ltv_animated_plotly.html"
fig.write_html(
    output_html,
    include_plotlyjs=True,
    full_html=True,
    config={
        "displayModeBar": True,
        "displaylogo": False,
        "modeBarButtonsToRemove": ["lasso2d", "select2d"]
    }
)

print(f"✓ Interactive animation saved to: {output_html}")
print("  Open this file in any modern browser — it has full play/pause/scrub controls.")
print("  You can also hover over points for details and click legend items to filter.")

# Also save a nice static PNG of the final frame (2024-Q4) for quick preview
fig_final = px.scatter(
    df[df["quarter"] == "2024-Q4"],
    x="fico", y="ltv",
    color="risk_segment",
    size="loan_amount",
    size_max=16,
    color_discrete_map=color_map,
    category_orders={"risk_segment": ["Super Prime", "Prime", "Near Prime", "Subprime"]},
    range_x=[575, 855],
    range_y=[48, 107],
    title="FICO vs LTV — Final Quarter (2024-Q4) | Static Preview",
    height=680,
    width=1000,
)
fig_final.update_layout(shapes=shapes, annotations=annotations)
fig_final.write_image("fico_ltv_final_quarter_preview.png", scale=2)
print("✓ Static preview saved to: fico_ltv_final_quarter_preview.png (2x resolution)")